INSERT INTO Brand (name) VALUES ('Samsung')
INSERT INTO Brand (name) VALUES ('LG')
INSERT INTO Brand (name) VALUES ('Panasonic')
INSERT INTO Brand (name) VALUES ('HP')
INSERT INTO Brand (name) VALUES ('Kangaroo')
INSERT INTO Button (_id, name, code, remote) VALUES (1, 'Menu', X'8081FEFF00010203', 1)
INSERT INTO Button (_id, name, code, remote) VALUES (2, 'Power', X'8081FEFF000102', 2)
INSERT INTO Button (_id, name, code, remote) VALUES (3, 'Power', X'8081FEFF000102', 3)
INSERT INTO Button (_id, name, code, remote) VALUES (4, 'Power', X'8081FEFF000102', 4)
INSERT INTO Remote (_id, name, isTemplate, brand, type) VALUES (1, 'Bedroom TV', 0, 'Samsung', 'TV')
INSERT INTO Remote (_id, name, isTemplate, brand, type) VALUES (2, null, 1, 'Samsung', 'TV')
INSERT INTO Remote (_id, name, isTemplate, brand, type) VALUES (3, null, 1, 'Samsung', 'TV')
INSERT INTO Remote (_id, name, isTemplate, brand, type) VALUES (4, null, 1, 'Samsung', 'TV')
INSERT INTO Type (name) VALUES ('TV')
INSERT INTO Type (name) VALUES ('AC')
INSERT INTO Type (name) VALUES ('Projector')
INSERT INTO Type (name) VALUES ('Fan')
INSERT INTO Type (name) VALUES ('TV Box')